# Generated by Django 4.2.27 on 2026-01-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='departments', to='faculty.teacher'),
        ),
    ]
